<?php

namespace Illumina\AbpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HealthvaultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthvaultRepository extends EntityRepository
{
}
